<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Mappa Mercia</title>
	<link rel="stylesheet" href="/style/main.css" type="text/css">
	<!--[if lt IE 7]>
		<script src="/scripts/pngfix.js" type="text/javascript"></script>
	<![endif]-->
</head>

<body>
	<div id="header">
		<img src="/style/header_map.png" alt="Logo showing a map" id="header_map">
		<a href="/" rel="start" title="Back to homepage"><img src="/style/header_title.png" alt="Mappa Mercia" id="header_title"></a>
	</div>

	<!--#include virtual="../main_menu.html.inc"-->
