<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Mappa Mercia</title>

	<link rel="icon" type="image/png" href="/style/site-icon.png">

	<!-- link rel="stylesheet" href="/style/base.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/style/default.css" type="text/css" media="screen" -->

	<link rel="stylesheet" href="/style/print-base.css" type="text/css" media="print,screen">
	<link rel="stylesheet" href="/style/print-default.css" type="text/css" media="print,screen"> 
</head>

<body>
	<!--#include virtual="header.shtml.inc"-->
