	</div>

	<p class="Copyright">
		Map data by <a href="http://www.openstreetmap.org/" title="OpenStreetMap">OpenStreetMap</a> &amp; Contributors 
		(<a href="http://creativecommons.org/licenses/by-sa/2.0/" rel="copyright" title="Creative Commons Attribution-ShareAlike 2.0">CC-BY-SA</a>); 
		All other content available under <a href="http://creativecommons.org/licenses/by-sa/3.0/" rel="copyright" title="Creative Commons Attribution-ShareAlike 3.0">CC-BY-SA</a>
	</p>
	<address class="Contact">Contact: <a href="mailto:info@mappa-mercia.org">info@mappa-mercia.org</a></address>
</body>
</html>
