<div id="header">
	<img src="/style/header_map.png" alt="Logo showing a map" id="header_map">
	<a href="/" rel="start" title="Back to homepage"><img src="/style/header_title.png" alt="Mappa Mercia" id="header_title"></a>
</div>

<!--#include virtual="../main_menu.html.inc"-->

<!--[if IE 6]>
<div style="position: absolute; right: 80px; top: 80px; padding: 10px; border: 2px solid black; background-color: #ffd43d; font-weight: bold; z-index: 100;">
	<a href="/deprecated_browser.html">Why is this website so ugly and does not work properly?</a>
</div>
<![endif]-->

<div id="body">
