<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Mappa Mercia</title>

	<link rel="icon" type="image/png" href="/style/site-icon.png">

	<link rel="stylesheet" href="/style/base.css" type="text/css">
	<link rel="stylesheet" href="/style/map.css" type="text/css">
	<!--[if IE 6]><link rel="stylesheet" href="/style/ie6-fix.css" type="text/css"><![endif]-->

	<script src="http://openlayers.org/api/OpenLayers.js" type="text/javascript"></script>
	<script src="/scripts/OpenStreetMap.js" type="text/javascript"></script>
	<script src="/scripts/map.js" type="text/javascript"></script>
	<!--[if IE 6]><script src="/scripts/ie6-fix.js" type="text/javascript"></script><![endif]-->
	<!--[if IE 7]><script src="/scripts/ie7-fix.js" type="text/javascript"></script><![endif]-->
</head>

<body>
	<!--#include virtual="header.shtml.inc"-->

	<div id="map">
		<noscript>
			<div style="padding-left: 15px">
				<h1>Javascript not found</h1>

				<p>I am sorry but the map requires Javascript.<br>
				Your browser does not support Javascript or you have disabled it.<br>
				Please enable it to view the map.
				</p>
			</div>
		</noscript>
	</div>
	<div id="sidebar" class="SidebarVisible">
		<div id="sidebar_toggle">&laquo;</div>
