#!/usr/bin/env python

import MySQLdb
import cgi
import re

def main():
	print "Content-type: text/html\n"
	form = cgi.FieldStorage()

	values = {}
	values["id"] = form.getfirst("id", "")

	# Check that parameters have a valid format:
	if not re.match(r"^\d+$", values["id"]):
		print "invalid or missing id"
		return
	
	conn = MySQLdb.connect("localhost", user="osb", passwd="osb12", db="osb")
	curs = conn.cursor()
	curs.execute("UPDATE bugs SET type = 1, close_date = NOW() WHERE id = %(id)s", values)
	conn.commit()

	print "bug closed"

main()
