#!/usr/bin/env python

import MySQLdb
import cgi

def main():
	print "Content-type: text/html\n"
	form = cgi.FieldStorage()
	values = {}
	values["id"] = form["id"].value
	values["text"] = form["text"].value
	
	conn = MySQLdb.connect("localhost", user="osb", passwd="osb12", db="osb")
	curs = conn.cursor()
	curs.execute("UPDATE bugs SET type = 0, text = CONCAT(text, '<hr />', %(text)s) WHERE id = %(id)s", values)
	conn.commit()

main()
