#!/usr/bin/env python

import MySQLdb
import cgi
import re

def main():
	print "Content-type: text/javascript\n"
	form = cgi.FieldStorage()

	values = {}
	values["b"] = form.getfirst("b", "")
	values["t"] = form.getfirst("t", "")
	values["l"] = form.getfirst("l", "")
	values["r"] = form.getfirst("r", "")

	# Check that parameters have a valid format:
	coord_exp = re.compile(r"^-?\d{1,3}(\.\d+)?$")
	for k, v in values.iteritems():
		if not coord_exp.match(v) or not (-180 <= float(v) and float(v) <= 180):
			print "/*invalid or missing %s*/" % k
			return
	
	conn = MySQLdb.connect("localhost", user="osb", passwd="osb12", db="osb")
	curs = conn.cursor)
	curs.execute("SELECT * FROM bugs WHERE %(b)s <= lat and lat <= %(t)s and %(l)s <= lon and lon <= %(r)s", values)
	for c in curs:
		print "putAJAXMarker(%i, %f, %f, '%s', %i);" % c[0:5]

main()
