<ul id="main_menu">
<li><a href="/maps.shtml" accesskey="m" title="The Maps">The Maps</a>
	<ul>
		<li><a href="/standard-map.shtml" title="Standard Map">Standard&nbsp;Map</a></li>
		<li><a href="/cycle-map.shtml" title="Cycle Map">Cycle&nbsp;Map</a></li>
		<li><a href="/public-transport-map.shtml" title="Public Transport Map">Public&nbsp;Transport&nbsp;Map</a></li>
	</ul>
</li>
<li><a href="/openstreetbugs.shtml" accesskey="r" title="Report Errors">Report Errors</a></li>
<li><a href="/contribute.shtml" accesskey="c" title="Contribute!">Contribute!</a></li>
<li><a href="/use.shtml" accesskey="u" title="Use the Map">Use the Map</a></li>
<li><a href="/projects.shtml" accesskey="p" title="Projects">Projects</a></li>
<li><a href="http://blog.mappa-mercia.org/" accesskey="b" title="Blog">Blog</a></li>
<li><a href="/about.shtml" accesskey="a" title="About">About</a></li>
<li><a href="/press.shtml" accesskey="e" title="Press">Press</a></li>
<li><a href="/contact.shtml" accesskey="t" title="Contact">Contact</a></li>
</ul>
