<ul id="main_menu">
<li><a href="/map.shtml" accesskey="m" title="The Map">The Map</a></li>
<li><a href="/openstreetbugs.shtml" accesskey="r" title="Report Errors">Report Errors</a></li>
<li><a href="/contribute.shtml" accesskey="c" title="Contribute!">Contribute!</a></li>
<li><a href="/projects.shtml" accesskey="p" title="Projects">Projects</a></li>
<li><a href="/about.shtml" accesskey="a" title="About">About</a></li>
<li><a href="/links.shtml" accesskey="l" title="Links">Links</a></li>
<li><a href="/press.shtml" accesskey="e" title="Press">Press</a></li>
<li><a href="/contact.shtml" accesskey="t" title="Contact">Contact</a></li>
</ul>
